import { Dimensions, StyleSheet } from 'react-native';

// Theme colors based on brand guidelines
export const colors = {
  primary: '#2cb673',          // vibrant green for primary elements
  accent: '#b1e2c6',           // lighter green for accents
  background: '#ebf8f1',       // soft greenish-white for background
  backgroundDarker: '#b1e2c6', // slightly darker background for contrast
  backgroundLight: '#ebf8f1',  // light green for sections
  text: '#1B5E20',             // deep green for text
  border: '#b1e2c6',           // light green for borders
  footerBg: '#2cb673',         // vibrant green for footer background
  footerText: '#ebf8f1',       // light text for footer
  hover: '#1e8f5a',            // hover state color
  white: 'white',
  black: 'black',
  grey: '#555',
  lightGrey: '#e0e0e0',
  error: '#e53935',            // Red for error states and logout
  overlay: 'rgba(0,0,0,0.5)',
  warning: '#FFA500', // Added warning color
  vacationApproved: '#4dabf7',
};

export const styles = StyleSheet.create({
  // Core layout styles
  container: {
    flex: 1,
    position: 'relative',
    backgroundColor: colors.background,
  },
  mainContent: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  welcomeText: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 16,
    color: colors.primary,
  },
  toggleButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 10,
    padding: 8,
  },
  
  // Sidebar styles
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.overlay,
    zIndex: 10,
  },
  sidebar: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: '70%',
    backgroundColor: colors.backgroundLight,
    zIndex: 20,
    shadowColor: colors.black,
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  sidebarHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.primary,
  },
  sidebarTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.white,
  },
  sidebarLinks: {
    flex: 1,
  },
  sidebarLink: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sidebarLinkText: {
    fontSize: 16,
    marginLeft: 10,
    color: colors.text,
  },
  
  // Orders styles (used in index.tsx)
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginTop: 20,
    marginBottom: 10,
    alignSelf: 'flex-start',
  },
  ordersMainList: {
    width: '100%',
    flex: 1,
    marginTop: 10,
  },
  ordersContentContainer: {
    paddingBottom: 20,
  },
  orderCard: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 16,
    marginBottom: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  orderCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.accent,
    marginBottom: 12,
  },
  orderCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginLeft: 10,
  },
  orderDetailItem: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'center',
  },
  orderDetailLabel: {
    width: '30%',
    fontSize: 15,
    color: colors.grey,
    fontWeight: '500',
  },
  orderDetailValue: {
    fontSize: 15,
    color: colors.text,
    flex: 1,
  },
  actionButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  actionButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  orderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.accent,
  },
  orderItemText: {
    marginLeft: 10,
    fontSize: 16,
    color: colors.text,
  },
  
  // Settings styles
  settingsList: {
    width: '100%',
    flex: 1,
    marginTop: 10,
  },
  settingsContentContainer: {
    paddingBottom: 20,
  },
  settingItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.white,
    margin: 10,
    borderRadius: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingTitle: {
    fontSize: 16,
    marginLeft: 10,
    color: colors.text,
  },
  settingTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  
  // User profile section in settings
  userInfoContainer: {
    backgroundColor: colors.white,
    padding: 20,
    margin: 10,
    borderRadius: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  userTextInfo: {
    marginLeft: 15,
    flex: 1,
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 5,
  },
  userDetail: {
    fontSize: 14,
    color: colors.grey,
    marginBottom: 3,
  },
  loginButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    padding: 15,
    margin: 10,
    borderRadius: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  loginButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignSelf: 'flex-start',
  },
  statusText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: 'bold',
  },

  phoneLink: {
    color: colors.primary,
    textDecorationLine: 'underline',
  },
  disabledButton: {
    backgroundColor: colors.grey,
    opacity: 0.7,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    marginTop: 40,
  },
  emptyStateText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginTop: 20,
  },
  emptyStateSubtext: {
    fontSize: 16,
    color: colors.grey,
    marginTop: 10,
    textAlign: 'center',
  },
  
  chatButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 10,
    padding: 8,
  },

  mapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  backButton: {
    padding: 10,
    marginRight: 10,
  },
  mapContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 16,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  placeholderMap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    borderRadius: 8,
    padding: 20,
    marginBottom: 16,
  },
  mapPlaceholder: {
    textAlign: 'center',
    color: colors.grey,
    marginTop: 20,
    padding: 10,
  },
  mapDestinationLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    marginTop: 16,
  },
  mapDestinationText: {
    fontSize: 18,
    color: colors.primary,
    marginTop: 8,
    marginBottom: 16,
    textAlign: 'center',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: colors.background,
    padding: 24,
    borderRadius: 12,
    width: 320,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 16,
    color: colors.grey,
    marginBottom: 12,
  },
  pickerContainer: {
    width: 180,
    marginBottom: 6,
  },
  shiftDurationText: {
    marginTop: 10,
    fontWeight: 'bold',
  },
  buttonRow: {
    flexDirection: 'row',
    marginTop: 18,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    marginRight: 10,
  },
  secondaryButton: {
    backgroundColor: colors.grey,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  buttonText: {
    color: colors.white,
    fontWeight: 'bold',
  },

  orderDetailSection: {
    marginBottom: 20,
    backgroundColor: colors.backgroundLight,
    borderRadius: 8,
    padding: 15,
  },
  sectionTitle1: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.primary,
    marginBottom: 10,
  },
  tipContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  tipAmount: {
    marginLeft: 8,
    fontSize: 15,
    color: colors.primary,
    fontWeight: 'bold',
  },

  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -60,
  },
  awaitingOrderText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
    marginTop: 20,
  },
  historyOrderCard: {
    backgroundColor: colors.white,
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
    marginHorizontal: 10,
    width: '94%',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: colors.lightGrey,
    elevation: 0,
  },
  
  historyDetailItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
    flexWrap: 'wrap',
    paddingVertical: 4,
  },
  
  historyDetailLabel: {
    fontSize: 15,
    fontWeight: 'bold',
    color: colors.text,
    marginRight: 10,
    minWidth: 90,
  },
  
  historyDetailValue: {
    fontSize: 15,
    color: colors.text,
    flex: 1,
  },

  photoThumbnailContainer: {
    alignItems: 'center',
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.backgroundLight,
    paddingTop: 16,
  },

  photoThumbnail: {
    width: '100%',
    height: 140,
    borderRadius: 8,
  },
  deliveryPhoto: {
    width: '100%',
    height: 250,
    borderRadius: 8,
    marginTop: 8,
  },
  noPhotoContainer: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: colors.backgroundLight,
    borderRadius: 8,
    marginTop: 10,
  },
  noPhotoText: {
    color: colors.error,
    textAlign: 'center',
    marginTop: 10,
    fontSize: 15,
  },

  faqItem: {
    backgroundColor: colors.white,
    borderRadius: 8,
    marginBottom: 15,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  faqQuestion: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
  },
  faqQuestionText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.text,
    flex: 1,
  },
  faqAnswer: {
    padding: 15,
    backgroundColor: colors.backgroundLight,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  faqAnswerText: {
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
  },
  bulletPoint: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 8,
    paddingRight: 10,
  },
  bulletText: {
    fontSize: 15,
    color: colors.text,
    marginLeft: 8,
    flex: 1,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginTop: 12,
    marginBottom: 4,
  },
  contactSection: {
    marginTop: 30,
    marginBottom: 40,
    backgroundColor: colors.white,
    padding: 20,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  contactTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
    marginBottom: 8,
  },
  contactText: {
    fontSize: 14,
    color: colors.grey,
    textAlign: 'center',
    marginBottom: 20,
  },
  phoneButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: '100%',
  },
  phoneButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  scrollContainer: {
    flex: 1,
    width: '100%',
  },
  scrollContent: {
    paddingVertical: 20,
  },

  contactButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 15,
  },
  contactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    marginHorizontal: 5,
  },
  contactButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  // Add these styles to your existing styles.ts file

calendarContainer: {
  flex: 1,
  width: '100%',
},
calendar: {
  marginBottom: 20,
  borderRadius: 10,
  borderWidth: 1,
  borderColor: colors.border,
  backgroundColor: colors.white,
},
calendarLegend: {
  flexDirection: 'row',
  justifyContent: 'space-around',
  paddingVertical: 10,
  marginBottom: 10,
  backgroundColor: colors.white,
  borderRadius: 8,
  borderWidth: 1,
  borderColor: colors.border,
},
legendItem: {
  flexDirection: 'row',
  alignItems: 'center',
},
legendColorBox: {
  width: 16,
  height: 16,
  borderRadius: 4,
  marginRight: 8,
},
legendText: {
  fontSize: 14,
  color: colors.text,
},
vacationButton: {
  position: 'absolute',
  top: 20,
  right: 20,
  zIndex: 10,
  padding: 8,
},
shiftInputContainer: {
  marginBottom: 16,
},
shiftInputLabel: {
  fontSize: 16,
  color: colors.text,
  marginBottom: 8,
},
shiftTimeInput: {
  borderWidth: 1,
  borderColor: colors.border,
  borderRadius: 8,
  padding: 12,
  fontSize: 16,
  backgroundColor: colors.white,
},
shiftSubmitButton: {
  backgroundColor: colors.primary,
  paddingVertical: 12,
  paddingHorizontal: 20,
  borderRadius: 8,
  alignItems: 'center',
  marginTop: 16,
},
shiftSubmitButtonText: {
  color: colors.white,
  fontSize: 16,
  fontWeight: 'bold',
},
calendarDateText: {
  fontSize: 18,
  fontWeight: 'bold',
  color: colors.primary,
  marginBottom: 16,
  textAlign: 'center',
},
upcomingShiftsContainer: {
  backgroundColor: colors.white,
  borderRadius: 10,
  padding: 16,
  marginBottom: 20,
  borderWidth: 1,
  borderColor: colors.border,
},
upcomingShiftsTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: colors.text,
  marginBottom: 16,
},
upcomingShiftItem: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingVertical: 12,
  borderBottomWidth: 1,
  borderBottomColor: colors.border,
},
upcomingShiftDetails: {
  flex: 1,
  marginLeft: 12,
},
upcomingShiftDate: {
  fontSize: 16,
  fontWeight: 'bold',
  color: colors.text,
},
upcomingShiftTime: {
  fontSize: 14,
  color: colors.grey,
  marginTop: 4,
},
upcomingShiftStatus: {
  paddingHorizontal: 10,
  paddingVertical: 5,
  borderRadius: 12,
},
noShiftsText: {
  fontSize: 16,
  color: colors.grey,
  textAlign: 'center',
  paddingVertical: 16,
  fontStyle: 'italic',
},

// Calendar day styles
calendarDayRow: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 14,
  paddingVertical: 6,
  paddingHorizontal: 10,
  borderRadius: 8,
},
calendarDayText: {
  width: 48,
  color: colors.grey,
  fontWeight: 'bold',
  fontSize: 16,
  textAlign: 'right',
  marginRight: 10,
},
calendarDayCircle: {
  width: 44,
  height: 44,
  borderRadius: 22,
  alignItems: 'center',
  justifyContent: 'center',
  marginLeft: 8,
},
calendarDayNumber: {
  fontSize: 18,
},
calendarShiftInfo: {
  flexDirection: 'row',
  alignItems: 'center',
  marginLeft: 14,
},
calendarShiftTime: {
  fontSize: 14,
  fontWeight: 'bold',
  marginRight: 6,
},
calendarShiftDuration: {
  fontSize: 13,
  fontWeight: 'bold',
},
modalContent: {
  backgroundColor: colors.white,
  borderRadius: 10,
  padding: 20,
  width: '90%',
  maxHeight: '80%',
  shadowColor: colors.black,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.25,
  shadowRadius: 3.84,
  elevation: 5,
},
modalCloseButton: {
  alignSelf: 'flex-end',
  padding: 10,
},
webViewContainer: {
  width: '100%',
  height: 300,
  borderRadius: 8,
  overflow: 'hidden',
  marginBottom: 10,
},
loadingOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: 'rgba(255, 255, 255, 0.7)',
  borderRadius: 8,
},
mapButtonContainer: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  marginBottom: 10,
  backgroundColor: colors.backgroundLight,
  borderRadius: 8,
  padding: 4,
},
mapButton: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
  padding: 8,
  borderRadius: 6,
  flexDirection: 'row',
  marginHorizontal: 2,
},
mapButtonActive: {
  backgroundColor: colors.primary,
},
mapButtonText: {
  marginLeft: 4,
  fontSize: 12,
  color: colors.text,
},
mapButtonTextActive: {
  color: 'white',
},
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingTop: 40,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 0,
    backgroundColor: colors.background,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.text,
    textAlign: 'center',
    flex: 1,
  },
  plusButton: {
    position: 'absolute',
    right: 18,
    top: 40,
    padding: 6,
  },
  chatPlusButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    padding: 8,
    zIndex: 10,
  },
  chatRoom: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGrey,
    backgroundColor: colors.white,
  },
  chatRoomText: {
    fontSize: 18,
    color: colors.text,
  },
  chatHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.background,
    minHeight: 64,
  },
  chatHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.primary, // green!
  },
  map: {
    flex: 1,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  loader: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapToggleButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 10,
    padding: 8,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderRadius: 20,
  },
  mapModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  mapModalContent: {
    backgroundColor: 'white',
    padding: 24,
    borderRadius: 12,
    alignItems: 'center',
    minWidth: 250,
  },
  chatMessageSender: {
    fontWeight: 'bold',
    color: colors.primary,
    marginRight: 8,
    fontSize: 15,
    minWidth: 48,
  },

  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.lightGrey,
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    fontSize: 16,
    backgroundColor: colors.backgroundLight,
    marginRight: 8,
  },

  // Calendar week navigation
  weekNavContainer: {
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between',
  },

  // Calendar styles
  calendarPadding: {
    paddingVertical: 10, 
    paddingHorizontal: 0,
  },
  transparentBackground: {
    backgroundColor: 'transparent',
  },
  
  // Icon styles
  iconRightMargin: {
    marginRight: 6,
  },

  // Text styles
  warningText: {
    color: colors.warning,
  },
  greyText: {
    color: colors.grey,
  },
  normalText: {
    color: colors.text,
  },
  whiteText: {
    color: colors.white,
  },
  
  // Form label styles
  formLabel: {
    marginBottom: 6,
  },
  boldFormLabel: {
    marginBottom: 6, 
    fontWeight: 'bold',
  },
  spacedFormLabel: {
    marginBottom: 6, 
    marginTop: 8,
  },
  durationText: {
    marginTop: 10, 
    fontWeight: 'bold',
  },
  errorText: {
    marginTop: 10, 
    color: colors.error, 
    textAlign: 'center',
  },

  // Button states
  activeButton: {
    opacity: 1,
  },
  inactiveButton: {
    opacity: 0.5,
  },
  routeLoadingIndicator: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },

  loadingText: {
    marginLeft: 8,
    color: colors.text,
    fontSize: 14,
  },
  startNavigationContainer: {
    position: 'absolute',
    bottom: 30,
    alignSelf: 'center',
    zIndex: 10,
  },
  startNavigationButton: {
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  startNavigationText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 8,
  },
  input: {
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 10,
    width: '100%',
  },
  recalculationIndicator: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 20,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  pullRefreshIndicator: {
    position: 'absolute',
    top: 40,
    left: '50%',
    transform: [{ translateX: -24 }],
    width: 48,
    height: 48,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 24,
    zIndex: 10,
    padding: 0,
  },
  pullRefreshZone: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  height: 60,
  zIndex: 5,
  },
  pullRefreshText: {
    color: colors.text,
    fontSize: 14,
    marginTop: 8,
  },
  pullRefreshArrow: {
    marginTop: 2,
  },
  recenterButtonContainer: {
    position: 'absolute',
    bottom: 30,           // Move to bottom
    right: 20,            // Keep right
    zIndex: 20,
    backgroundColor: colors.primary,
    borderRadius: 20,
    overflow: 'hidden',
    elevation: 3,
  },
  passwordEyeIcon: {
  position: 'absolute',
  right: 14,
  top: 10,
  zIndex: 2,
},
loginFieldsContainer: {
  marginVertical: 20,
  width: '100%',
  alignItems: 'center',
},
passwordInputWrapper: {
  position: 'relative',
  width: '100%',
},
inputSettings: {
  height: 40,
  borderColor: '#ccc',
  borderWidth: 1,
  borderRadius: 8,
  paddingHorizontal: 10,
  marginBottom: 10,
  width: '100%',
  backgroundColor: 'white',
},
loginButtonSettings: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#2cb673',
  padding: 15,
  marginVertical: 5,
  borderRadius: 8,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.2,
  shadowRadius: 2,
  elevation: 2,
  width: '100%',
},
signUpButton: {
  backgroundColor: "#1976d2",
  marginTop: 10,
},
userInfoContainerWide: {
  backgroundColor: colors.white,
  padding: 20,
  marginVertical: 10,
  borderRadius: 8,
  shadowColor: colors.black,
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 2,
  flexDirection: 'row',
  alignItems: 'center',
  width: '100%',
  alignSelf: 'center',
  maxWidth: 420,
},
settingItemWide: {
  padding: 15,
  borderBottomWidth: 1,
  borderBottomColor: colors.border,
  backgroundColor: colors.white,
  marginVertical: 10,
  borderRadius: 8,
  shadowColor: colors.black,
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 2,
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  width: '100%',
  alignSelf: 'center',
  maxWidth: 420,
},
chatMessageRow: {
  flexDirection: 'row',
  alignItems: 'flex-start',
  marginBottom: 12,
  paddingHorizontal: 10,
  paddingVertical: 2,
  backgroundColor: 'transparent',
},
chatMessageBubble: {
  maxWidth: '85%',
  backgroundColor: colors.backgroundLight,
  borderRadius: 12,
  padding: 10,
  shadowColor: colors.black,
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.05,
  shadowRadius: 2,
  elevation: 1,
  flexShrink: 1,
},
chatMessageHeader: {
  flexDirection: 'row',
  alignItems: 'center',
  marginBottom: 2,
  flexWrap: 'wrap',
},

chatMessageTimestamp: {
  color: colors.grey,
  fontSize: 12,
  marginLeft: 'auto',
},
chatMessageText: {
  color: colors.text,
  fontSize: 15,
  flexShrink: 1,
  flexWrap: 'wrap',
},
chatMessageImage: {
  width: 120,
  height: 90,
  borderRadius: 8,
  marginTop: 4,
},
});